# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_walking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False},
        ),
    ]
